import type {Consumo} from './types'

type DataPorProvincia = Record<string, {hogares: number, consumo: number}>

// consumo (GWH / año)
export const dataPorProvincia: DataPorProvincia = {
  Pastaza: {
    hogares: 28_327,
    consumo: 54
  }
}

export const consumos: Consumo[] = [
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 1,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 13.5,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 4.5,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.05,
    'Consumo Laptop': 0,
    'Consumo Celular': 4.5,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 23.55,
    'Consumo Planilla': 83,
    Hogares: 138
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 2,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 34.2,
    'Consumo Licuadora': 1.1475,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 4.29,
    'Consumo Tv LCD': 6.075,
    'Consumo PC Escritorio': 0.675,
    'Consumo Radio': 2.205,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.15,
    'Consumo Ducha Eléctrica': 1.125,
    'Consumo Lavadora de ropa': 0.275,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 3.015,
    'Consumo Laptop': 0.0675,
    'Consumo Celular': 2.295,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 55.52,
    'Consumo Planilla': 139,
    Hogares: 172
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 3,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 33,
    'Consumo Licuadora': 8.625,
    'Consumo Microondas': 2.6785714286,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 2.4142857143,
    'Consumo Tv LCD': 3.8571428571,
    'Consumo PC Escritorio': 1.2857142857,
    'Consumo Radio': 1,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.1071428571,
    'Consumo Ducha Eléctrica': 4.4642857143,
    'Consumo Lavadora de ropa': 1.4666666667,
    'Consumo Secadora de ropa': 0.3142857143,
    'Consumo Focos': 4.9285714286,
    'Consumo Laptop': 0.5142857143,
    'Consumo Celular': 5.3714285714,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 70.0273809524,
    'Consumo Planilla': 112.5714285714,
    Hogares: 16
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 5,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 3,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 10,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 25,
    'Consumo PC Escritorio': 180,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 3.6666666667,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 8,
    'Consumo Laptop': 4.2,
    'Consumo Celular': 5.8,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 275.6666666667,
    'Consumo Planilla': 171.0666666667,
    Hogares: 103
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 5,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 32.7272727273,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 4.0909090909,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 2.1272727273,
    'Consumo Tv LCD': 6.2727272727,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0.1909090909,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.2045454545,
    'Consumo Ducha Eléctrica': 6.1363636364,
    'Consumo Lavadora de ropa': 1,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 5.7545454545,
    'Consumo Laptop': 0,
    'Consumo Celular': 2.7272727273,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 62.3568181818,
    'Consumo Planilla': 157.5563636364,
    Hogares: 825
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 9,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 18,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 2.925,
    'Consumo Tv LCD': 0,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 4.05,
    'Consumo Laptop': 3.6,
    'Consumo Celular': 3,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 32.7,
    'Consumo Planilla': 156,
    Hogares: 303
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 9,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.95,
    'Consumo Tv LCD': 3,
    'Consumo PC Escritorio': 4.5,
    'Consumo Radio': 2.1,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 11.25,
    'Consumo Lavadora de ropa': 8.8,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 16.8,
    'Consumo Laptop': 1.8,
    'Consumo Celular': 1.2,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 88.525,
    'Consumo Planilla': 208,
    Hogares: 13
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 14,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 18,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 2.925,
    'Consumo Tv LCD': 0,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 4.05,
    'Consumo Laptop': 3.6,
    'Consumo Celular': 3,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 32.7,
    'Consumo Planilla': 156,
    Hogares: 297
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 1,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 3.375,
    'Consumo Microondas': 11.25,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 6,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 22.5,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 4.5,
    'Consumo Laptop': 1.8,
    'Consumo Celular': 0.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 86.025,
    'Consumo Planilla': 80,
    Hogares: 25
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 1,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 1.35,
    'Consumo Microondas': 4.5,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 4.5,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 1.2,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 5.625,
    'Consumo Lavadora de ropa': 1.76,
    'Consumo Secadora de ropa': 1.32,
    'Consumo Focos': 3.6,
    'Consumo Laptop': 3.96,
    'Consumo Celular': 1.86,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 65.675,
    'Consumo Planilla': 101.504,
    Hogares: 13
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 1,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 28.8,
    'Consumo Licuadora': 0.675,
    'Consumo Microondas': 2.25,
    'Consumo Cocina de inducción': 6,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 5.07,
    'Consumo Tv LCD': 23.7,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0.84,
    'Consumo Videojuegos': 0.12,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 7.2,
    'Consumo Ducha Eléctrica': 5.625,
    'Consumo Lavadora de ropa': 6.16,
    'Consumo Secadora de ropa': 5.28,
    'Consumo Focos': 5.28,
    'Consumo Laptop': 2.16,
    'Consumo Celular': 1.86,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 101.02,
    'Consumo Planilla': 84.952,
    Hogares: 730
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 2,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 3.75,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 6,
    'Consumo PC Escritorio': 378,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 22.5,
    'Consumo Lavadora de ropa': 22,
    'Consumo Secadora de ropa': 22,
    'Consumo Focos': 18,
    'Consumo Laptop': 21.6,
    'Consumo Celular': 28.8,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 559.775,
    'Consumo Planilla': 480,
    Hogares: 228
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 2,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 33.6,
    'Consumo Licuadora': 3,
    'Consumo Microondas': 3,
    'Consumo Cocina de inducción': 2,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0.26,
    'Consumo Tv LCD': 6.5,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 1.12,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 36,
    'Consumo Ventilador': 0.125,
    'Consumo Ducha Eléctrica': 4.75,
    'Consumo Lavadora de ropa': 1.32,
    'Consumo Secadora de ropa': 0.44,
    'Consumo Focos': 4.38,
    'Consumo Laptop': 0.9,
    'Consumo Celular': 2.36,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 99.755,
    'Consumo Planilla': 142.4746666667,
    Hogares: 1835
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 2,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 2.25,
    'Consumo Microondas': 3.75,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 19,
    'Consumo PC Escritorio': 10.5,
    'Consumo Radio': 0.7,
    'Consumo Videojuegos': 1.2,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 7.5,
    'Consumo Lavadora de ropa': 11,
    'Consumo Secadora de ropa': 2.2,
    'Consumo Focos': 4.1,
    'Consumo Laptop': 0,
    'Consumo Celular': 2.8,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 101,
    'Consumo Planilla': 147.92,
    Hogares: 548
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 2,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 37.6666666667,
    'Consumo Licuadora': 1.375,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0.8333333333,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 6.3916666667,
    'Consumo Tv LCD': 2.8333333333,
    'Consumo PC Escritorio': 0.0416666667,
    'Consumo Radio': 3.85,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.0104166667,
    'Consumo Ducha Eléctrica': 2.5625,
    'Consumo Lavadora de ropa': 0.1222222222,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 4.0666666667,
    'Consumo Laptop': 0.6,
    'Consumo Celular': 2.5833333333,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 62.9368055556,
    'Consumo Planilla': 183.8222222222,
    Hogares: 5988
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 3,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 42,
    'Consumo Licuadora': 4.36875,
    'Consumo Microondas': 3.75,
    'Consumo Cocina de inducción': 10,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0.4875,
    'Consumo Tv LCD': 10,
    'Consumo PC Escritorio': 2.4375,
    'Consumo Radio': 2.45,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.25,
    'Consumo Ducha Eléctrica': 5.625,
    'Consumo Lavadora de ropa': 3.4833333333,
    'Consumo Secadora de ropa': 0.275,
    'Consumo Focos': 6.4875,
    'Consumo Laptop': 3.73125,
    'Consumo Celular': 4.8,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 100.1458333333,
    'Consumo Planilla': 143.2733333333,
    Hogares: 101
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 3,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 42,
    'Consumo Licuadora': 2.625,
    'Consumo Microondas': 7.5,
    'Consumo Cocina de inducción': 10.8333333333,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 6.0125,
    'Consumo Tv LCD': 26.5,
    'Consumo PC Escritorio': 18.75,
    'Consumo Radio': 2.1875,
    'Consumo Videojuegos': 2.6,
    'Consumo Aire Acondicionado': 90,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 41.25,
    'Consumo Lavadora de ropa': 12.1,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 13.2,
    'Consumo Laptop': 2.1,
    'Consumo Celular': 14.1,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 291.7583333333,
    'Consumo Planilla': 364.3866666667,
    Hogares: 13
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 3,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 26.6666666667,
    'Consumo Licuadora': 3.8083333333,
    'Consumo Microondas': 4.3611111111,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 5.5611111111,
    'Consumo Tv LCD': 8.2222222222,
    'Consumo PC Escritorio': 0.1666666667,
    'Consumo Radio': 0.7,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 1.4583333333,
    'Consumo Lavadora de ropa': 1.3444444444,
    'Consumo Secadora de ropa': 0.2444444444,
    'Consumo Focos': 3.5,
    'Consumo Laptop': 0.4,
    'Consumo Celular': 4.65,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 61.0833333333,
    'Consumo Planilla': 101.12,
    Hogares: 618
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 4,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 1.9852941176,
    'Consumo Microondas': 0.9705882353,
    'Consumo Cocina de inducción': 0.4411764706,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.2044117647,
    'Consumo Tv LCD': 18.3529411765,
    'Consumo PC Escritorio': 9.7941176471,
    'Consumo Radio': 0.5558823529,
    'Consumo Videojuegos': 0.0176470588,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.3529411765,
    'Consumo Ducha Eléctrica': 3.9705882353,
    'Consumo Lavadora de ropa': 5.6941176471,
    'Consumo Secadora de ropa': 2.3294117647,
    'Consumo Focos': 10.8176470588,
    'Consumo Laptop': 3.0705882353,
    'Consumo Celular': 5.1882352941,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 100.7455882353,
    'Consumo Planilla': 195.1435294118,
    Hogares: 52
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 4,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 28.3636363636,
    'Consumo Licuadora': 1.5068181818,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0.9090909091,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.4772727273,
    'Consumo Tv LCD': 5.5454545455,
    'Consumo PC Escritorio': 0.6818181818,
    'Consumo Radio': 4.0196969697,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 2.0454545455,
    'Consumo Lavadora de ropa': 0.7333333333,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 4.0181818182,
    'Consumo Laptop': 0.2181818182,
    'Consumo Celular': 4.1318181818,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 53.6507575758,
    'Consumo Planilla': 104.6424242424,
    Hogares: 338
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 6,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 38.6666666667,
    'Consumo Licuadora': 2.4916666667,
    'Consumo Microondas': 1.9444444444,
    'Consumo Cocina de inducción': 13.3333333333,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0.7222222222,
    'Consumo Tv LCD': 16.5555555556,
    'Consumo PC Escritorio': 8.8333333333,
    'Consumo Radio': 2.6444444444,
    'Consumo Videojuegos': 0.1777777778,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.0185185185,
    'Consumo Ducha Eléctrica': 5.4166666667,
    'Consumo Lavadora de ropa': 4.237037037,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 11.4111111111,
    'Consumo Laptop': 4.0666666667,
    'Consumo Celular': 9.4111111111,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 119.9305555556,
    'Consumo Planilla': 165.76,
    Hogares: 1267
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 6,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 3.825,
    'Consumo Microondas': 4.5,
    'Consumo Cocina de inducción': 81,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 7.41,
    'Consumo Tv LCD': 8.4,
    'Consumo PC Escritorio': 5.4,
    'Consumo Radio': 1.26,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 2.925,
    'Consumo Lavadora de ropa': 2.64,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 12.9,
    'Consumo Laptop': 2.88,
    'Consumo Celular': 4.2,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 173.34,
    'Consumo Planilla': 142.08,
    Hogares: 201
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 6,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 5.07,
    'Consumo Microondas': 0.25,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.82,
    'Consumo Tv LCD': 10.2,
    'Consumo PC Escritorio': 1.8,
    'Consumo Radio': 4.48,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 1.0266666667,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 6.92,
    'Consumo Laptop': 0.12,
    'Consumo Celular': 4.8,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 72.4866666667,
    'Consumo Planilla': 128.8586666667,
    Hogares: 1781
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 7,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 72,
    'Consumo Licuadora': 13.5,
    'Consumo Microondas': 45,
    'Consumo Cocina de inducción': 180,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 90,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 8.4,
    'Consumo Videojuegos': 4.8,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 11,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 36,
    'Consumo Laptop': 21.6,
    'Consumo Celular': 14.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 496.7,
    'Consumo Planilla': 432,
    Hogares: 18
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 7,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 33.8823529412,
    'Consumo Licuadora': 2.5279411765,
    'Consumo Microondas': 1.3235294118,
    'Consumo Cocina de inducción': 6.1764705882,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0.3441176471,
    'Consumo Tv LCD': 12.3529411765,
    'Consumo PC Escritorio': 3.4411764706,
    'Consumo Radio': 1.8529411765,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 2.6470588235,
    'Consumo Lavadora de ropa': 3.731372549,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 9.8823529412,
    'Consumo Laptop': 2.3294117647,
    'Consumo Celular': 7.9058823529,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 88.3975490194,
    'Consumo Planilla': 173.8635294118,
    Hogares: 136
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 7,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 20.5714285714,
    'Consumo Licuadora': 1.2857142857,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 3.0642857143,
    'Consumo Tv LCD': 5.1428571429,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 3.9,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 2.5142857143,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 6.7285714286,
    'Consumo Laptop': 0.7714285714,
    'Consumo Celular': 6.9428571429,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 50.9214285714,
    'Consumo Planilla': 124.5714285714,
    Hogares: 110
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 8,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 27,
    'Consumo Licuadora': 3.825,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.4625,
    'Consumo Tv LCD': 3,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 1.575,
    'Consumo Videojuegos': 0.6,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 5.625,
    'Consumo Lavadora de ropa': 2.75,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 5.475,
    'Consumo Laptop': 0.9,
    'Consumo Celular': 8.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 60.6125,
    'Consumo Planilla': 206.54,
    Hogares: 130
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 10,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 18,
    'Consumo Licuadora': 0.5625,
    'Consumo Microondas': 5.625,
    'Consumo Cocina de inducción': 45,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 0,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 3.3,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 2.4,
    'Consumo Laptop': 0,
    'Consumo Celular': 15,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 89.8875,
    'Consumo Planilla': 88,
    Hogares: 70
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 14,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 1.875,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.95,
    'Consumo Tv LCD': 2,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 3.5,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 8.8,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 4.8,
    'Consumo Laptop': 1.2,
    'Consumo Celular': 5.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 65.525,
    'Consumo Planilla': 122.1333333333,
    Hogares: 276
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 14,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 24,
    'Consumo Licuadora': 1.65,
    'Consumo Microondas': 10,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 10,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 1.4,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 4.4,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 13.4,
    'Consumo Laptop': 1.2,
    'Consumo Celular': 14.8,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 80.85,
    'Consumo Planilla': 150.1333333333,
    Hogares: 85
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 15,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 1.875,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.95,
    'Consumo Tv LCD': 2,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 3.5,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 8.8,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 4.8,
    'Consumo Laptop': 1.2,
    'Consumo Celular': 5.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 65.525,
    'Consumo Planilla': 122.1333333333,
    Hogares: 23
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 16,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 1.875,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.95,
    'Consumo Tv LCD': 2,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 3.5,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 8.8,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 4.8,
    'Consumo Laptop': 1.2,
    'Consumo Celular': 5.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 65.525,
    'Consumo Planilla': 122.1333333333,
    Hogares: 63
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Rural',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 16,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 0,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 0,
    'Consumo Laptop': 0,
    'Consumo Celular': 0,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 0,
    'Consumo Planilla': 640,
    Hogares: 53
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 1,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 1.575,
    'Consumo Microondas': 2.8125,
    'Consumo Cocina de inducción': 52.5,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 2.925,
    'Consumo Tv LCD': 15,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 7.03125,
    'Consumo Lavadora de ropa': 4.4,
    'Consumo Secadora de ropa': 2.75,
    'Consumo Focos': 14.625,
    'Consumo Laptop': 5.4,
    'Consumo Celular': 3.9,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 148.91875,
    'Consumo Planilla': 218,
    Hogares: 162
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 1,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 0,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 45,
    'Consumo Lavadora de ropa': 13.2,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 3.6,
    'Consumo Laptop': 1.8,
    'Consumo Celular': 0,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 100.725,
    'Consumo Planilla': 48,
    Hogares: 43
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 1,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 25.5,
    'Consumo Licuadora': 6.75,
    'Consumo Microondas': 30,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 24,
    'Consumo PC Escritorio': 15,
    'Consumo Radio': 0.7,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.75,
    'Consumo Ducha Eléctrica': 7.5,
    'Consumo Lavadora de ropa': 8.066666667,
    'Consumo Secadora de ropa': 4.4,
    'Consumo Focos': 8,
    'Consumo Laptop': 3.6,
    'Consumo Celular': 5,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 139.2666667,
    'Consumo Planilla': 121.8666667,
    Hogares: 67
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 1,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 1.575,
    'Consumo Microondas': 2.8125,
    'Consumo Cocina de inducción': 52.5,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 2.925,
    'Consumo Tv LCD': 15,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 7.03125,
    'Consumo Lavadora de ropa': 4.4,
    'Consumo Secadora de ropa': 2.75,
    'Consumo Focos': 14.625,
    'Consumo Laptop': 5.4,
    'Consumo Celular': 3.9,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 148.91875,
    'Consumo Planilla': 218,
    Hogares: 16
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 2,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 38.57142857,
    'Consumo Licuadora': 6.8625,
    'Consumo Microondas': 10.60714286,
    'Consumo Cocina de inducción': 12.85714286,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.114285714,
    'Consumo Tv LCD': 14.57142857,
    'Consumo PC Escritorio': 2.25,
    'Consumo Radio': 3.6,
    'Consumo Videojuegos': 0.0857142857,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 1.339285714,
    'Consumo Ducha Eléctrica': 11.16964286,
    'Consumo Lavadora de ropa': 3.771428571,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 9.535714286,
    'Consumo Laptop': 5.785714286,
    'Consumo Celular': 4.821428571,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 126.9428571,
    'Consumo Planilla': 179.44,
    Hogares: 88
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 2,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 10.8,
    'Consumo Microondas': 10.71428571,
    'Consumo Cocina de inducción': 25.71428571,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0.8357142857,
    'Consumo Tv LCD': 19.28571429,
    'Consumo PC Escritorio': 3.535714286,
    'Consumo Radio': 1.2,
    'Consumo Videojuegos': 0.1714285714,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 47.14285714,
    'Consumo Lavadora de ropa': 5.971428571,
    'Consumo Secadora de ropa': 0.2095238095,
    'Consumo Focos': 9.557142857,
    'Consumo Laptop': 12.08571429,
    'Consumo Celular': 12.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 195.8238095,
    'Consumo Planilla': 266.7085714,
    Hogares: 38
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 2,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 42.35294118,
    'Consumo Licuadora': 3.917647059,
    'Consumo Microondas': 6.397058824,
    'Consumo Cocina de inducción': 17.64705882,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 7.226470588,
    'Consumo Tv LCD': 9,
    'Consumo PC Escritorio': 7.411764706,
    'Consumo Radio': 3.829411765,
    'Consumo Videojuegos': 0.2823529412,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.4411764706,
    'Consumo Ducha Eléctrica': 6.176470588,
    'Consumo Lavadora de ropa': 5.564705882,
    'Consumo Secadora de ropa': 0.6470588235,
    'Consumo Focos': 10.68529412,
    'Consumo Laptop': 3.070588235,
    'Consumo Celular': 10.37647059,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 2.647058824,
    'Consumo Electrodomésticos': 137.6735294,
    'Consumo Planilla': 181.3835294,
    Hogares: 46
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 3,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 34.5,
    'Consumo Licuadora': 6.58125,
    'Consumo Microondas': 13.59375,
    'Consumo Cocina de inducción': 2.5,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 3.16875,
    'Consumo Tv LCD': 7.375,
    'Consumo PC Escritorio': 9.5625,
    'Consumo Radio': 2.8875,
    'Consumo Videojuegos': 0.35,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.09375,
    'Consumo Ducha Eléctrica': 5.15625,
    'Consumo Lavadora de ropa': 3.85,
    'Consumo Secadora de ropa': 1.008333333,
    'Consumo Focos': 8.0625,
    'Consumo Laptop': 2.625,
    'Consumo Celular': 8.388333333,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 109.7029167,
    'Consumo Planilla': 160.46,
    Hogares: 15
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 5,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 27.5625,
    'Consumo Microondas': 45.375,
    'Consumo Cocina de inducción': 60,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 21,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 5.25,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 28.125,
    'Consumo Lavadora de ropa': 26.4,
    'Consumo Secadora de ropa': 25.3,
    'Consumo Focos': 9,
    'Consumo Laptop': 9,
    'Consumo Celular': 5.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 298.4125,
    'Consumo Planilla': 344,
    Hogares: 19
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 5,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 5.11875,
    'Consumo Microondas': 2.8125,
    'Consumo Cocina de inducción': 22.5,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 2.925,
    'Consumo Tv LCD': 26.25,
    'Consumo PC Escritorio': 6.75,
    'Consumo Radio': 3.15,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 28.125,
    'Consumo Lavadora de ropa': 3.025,
    'Consumo Secadora de ropa': 0.55,
    'Consumo Focos': 11.8125,
    'Consumo Laptop': 3.6,
    'Consumo Celular': 13.8,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 166.41875,
    'Consumo Planilla': 186.5,
    Hogares: 642
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 5,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 10.5,
    'Consumo Microondas': 22.5,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 11.7,
    'Consumo Tv LCD': 12,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 2.8,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 37.5,
    'Consumo Lavadora de ropa': 5.133333333,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 13.2,
    'Consumo Laptop': 19.2,
    'Consumo Celular': 24,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 194.5333333,
    'Consumo Planilla': 155.52,
    Hogares: 142
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 5,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 28.8,
    'Consumo Licuadora': 0.72,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.95,
    'Consumo Tv LCD': 12.6,
    'Consumo PC Escritorio': 3.6,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 9.24,
    'Consumo Secadora de ropa': 2.64,
    'Consumo Focos': 6.84,
    'Consumo Laptop': 3.6,
    'Consumo Celular': 14.04,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 84.03,
    'Consumo Planilla': 208,
    Hogares: 1052
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 5,
    Ingreso: 'Más de 2400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 3.9,
    'Consumo Tv LCD': 0,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 7.2,
    'Consumo Laptop': 0,
    'Consumo Celular': 1.2,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 48.3,
    'Consumo Planilla': 56,
    Hogares: 87
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 6,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 0.5625,
    'Consumo Microondas': 1.5,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 2.925,
    'Consumo Tv LCD': 3,
    'Consumo PC Escritorio': 18,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.375,
    'Consumo Ducha Eléctrica': 24.375,
    'Consumo Lavadora de ropa': 7.7,
    'Consumo Secadora de ropa': 2.2,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0.9,
    'Consumo Celular': 3.75,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 103.0875,
    'Consumo Planilla': 152,
    Hogares: 44
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 9,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 365
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 9,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 54
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 9,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 152
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 9,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 23
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 13,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 19
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 13,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 104
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 13,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 16
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 14,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 31
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 14,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 59
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 14,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 104
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 15,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 57
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 15,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 32
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Femenina',
    'Tipo de Hogar': 16,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 1.125,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 36,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 25.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 1.8,
    'Consumo Laptop': 0,
    'Consumo Celular': 21.6,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 85.725,
    'Consumo Planilla': 96,
    Hogares: 15
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 1,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 9.9,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.3,
    'Consumo Tv LCD': 4,
    'Consumo PC Escritorio': 7.5,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 18.75,
    'Consumo Lavadora de ropa': 5.133333333,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 8.2,
    'Consumo Laptop': 0.6,
    'Consumo Celular': 1.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 92.78333333,
    'Consumo Planilla': 208,
    Hogares: 30
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 1,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 38.11764706,
    'Consumo Licuadora': 6.882352941,
    'Consumo Microondas': 6.617647059,
    'Consumo Cocina de inducción': 11.47058824,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.032352941,
    'Consumo Tv LCD': 10.05882353,
    'Consumo PC Escritorio': 8.205882353,
    'Consumo Radio': 0.9882352941,
    'Consumo Videojuegos': 0.3529411765,
    'Consumo Aire Acondicionado': 2.647058824,
    'Consumo Ventilador': 0.0477941176,
    'Consumo Ducha Eléctrica': 15.22058824,
    'Consumo Lavadora de ropa': 4.141176471,
    'Consumo Secadora de ropa': 1.035294118,
    'Consumo Focos': 8.082352941,
    'Consumo Laptop': 6.352941176,
    'Consumo Celular': 9.017647059,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 130.2713235,
    'Consumo Planilla': 180.0188235,
    Hogares: 324
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 1,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 5.625,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.95,
    'Consumo Tv LCD': 17,
    'Consumo PC Escritorio': 3,
    'Consumo Radio': 3.15,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.75,
    'Consumo Ducha Eléctrica': 24.375,
    'Consumo Lavadora de ropa': 22.73333333,
    'Consumo Secadora de ropa': 22,
    'Consumo Focos': 14.5,
    'Consumo Laptop': 4.8,
    'Consumo Celular': 10.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 166.2833333,
    'Consumo Planilla': 170.6666667,
    Hogares: 108
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 1,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 33.42857143,
    'Consumo Licuadora': 5.721428571,
    'Consumo Microondas': 16.17857143,
    'Consumo Cocina de inducción': 8.571428571,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.114285714,
    'Consumo Tv LCD': 19.28571429,
    'Consumo PC Escritorio': 2.892857143,
    'Consumo Radio': 2.55,
    'Consumo Videojuegos': 0.1714285714,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.4821428571,
    'Consumo Ducha Eléctrica': 20.08928571,
    'Consumo Lavadora de ropa': 5.264285714,
    'Consumo Secadora de ropa': 1.257142857,
    'Consumo Focos': 6.835714286,
    'Consumo Laptop': 10.41428571,
    'Consumo Celular': 11.22857143,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 145.4857143,
    'Consumo Planilla': 150.9714286,
    Hogares: 330
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 2,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 60,
    'Consumo Licuadora': 5.25,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 5,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 42,
    'Consumo PC Escritorio': 25.5,
    'Consumo Radio': 8.4,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 6,
    'Consumo Ducha Eléctrica': 33.75,
    'Consumo Lavadora de ropa': 7.333333333,
    'Consumo Secadora de ropa': 4.4,
    'Consumo Focos': 15.4,
    'Consumo Laptop': 31.2,
    'Consumo Celular': 19.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 263.6333333,
    'Consumo Planilla': 186.6666667,
    Hogares: 577
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 2,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 34.28571429,
    'Consumo Licuadora': 3.096428571,
    'Consumo Microondas': 4.464285714,
    'Consumo Cocina de inducción': 10.71428571,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.857142857,
    'Consumo Tv LCD': 9,
    'Consumo PC Escritorio': 8.785714286,
    'Consumo Radio': 2.3,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.25,
    'Consumo Ducha Eléctrica': 8.107142857,
    'Consumo Lavadora de ropa': 2.915873016,
    'Consumo Secadora de ropa': 0.0873015873,
    'Consumo Focos': 8.371428571,
    'Consumo Laptop': 2.485714286,
    'Consumo Celular': 6.657142857,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0.8571428571,
    'Consumo Electrodomésticos': 104.2353175,
    'Consumo Planilla': 162.4685714,
    Hogares: 1742
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 2,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 2.475,
    'Consumo Microondas': 0.9642857143,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 4.735714286,
    'Consumo Tv LCD': 6.214285714,
    'Consumo PC Escritorio': 1.285714286,
    'Consumo Radio': 4.5,
    'Consumo Videojuegos': 0.1714285714,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.9642857143,
    'Consumo Ducha Eléctrica': 12.32142857,
    'Consumo Lavadora de ropa': 3.771428571,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 10.07142857,
    'Consumo Laptop': 2.571428571,
    'Consumo Celular': 4.8,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 90.84642857,
    'Consumo Planilla': 209.1428571,
    Hogares: 576
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 2,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 52,
    'Consumo Licuadora': 3.95,
    'Consumo Microondas': 3.916666667,
    'Consumo Cocina de inducción': 1.666666667,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.733333333,
    'Consumo Tv LCD': 16.83333333,
    'Consumo PC Escritorio': 12.75,
    'Consumo Radio': 2.566666667,
    'Consumo Videojuegos': 0.1333333333,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.3541666667,
    'Consumo Ducha Eléctrica': 6.458333333,
    'Consumo Lavadora de ropa': 6.111111111,
    'Consumo Secadora de ropa': 1.588888889,
    'Consumo Focos': 6.733333333,
    'Consumo Laptop': 6.3,
    'Consumo Celular': 15.48333333,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 138.5791667,
    'Consumo Planilla': 148.7733333,
    Hogares: 621
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 3,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 39.27272727,
    'Consumo Licuadora': 5.788636364,
    'Consumo Microondas': 3.409090909,
    'Consumo Cocina de inducción': 13.63636364,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 4.077272727,
    'Consumo Tv LCD': 11.72727273,
    'Consumo PC Escritorio': 13.09090909,
    'Consumo Radio': 4.868181818,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.4886363636,
    'Consumo Ducha Eléctrica': 18.13636364,
    'Consumo Lavadora de ropa': 3.2,
    'Consumo Secadora de ropa': 2.2,
    'Consumo Focos': 9.245454545,
    'Consumo Laptop': 1.755,
    'Consumo Celular': 9.272727273,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 4.909090909,
    'Consumo Electrodomésticos': 143.47,
    'Consumo Planilla': 183.5781818,
    Hogares: 69
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 3,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 3.4575,
    'Consumo Microondas': 11.75,
    'Consumo Cocina de inducción': 15,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 3.835,
    'Consumo Tv LCD': 17.2,
    'Consumo PC Escritorio': 6.45,
    'Consumo Radio': 3.71,
    'Consumo Videojuegos': 0.2,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 2.5,
    'Consumo Ducha Eléctrica': 8.4375,
    'Consumo Lavadora de ropa': 6.38,
    'Consumo Secadora de ropa': 1.906666667,
    'Consumo Focos': 10,
    'Consumo Laptop': 4.5,
    'Consumo Celular': 10.48,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 141.8066667,
    'Consumo Planilla': 162.2053333,
    Hogares: 220
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 3,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 32.4,
    'Consumo Licuadora': 5.4,
    'Consumo Microondas': 117,
    'Consumo Cocina de inducción': 6,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 12.285,
    'Consumo Tv LCD': 6.6,
    'Consumo PC Escritorio': 0.45,
    'Consumo Radio': 1.8375,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.525,
    'Consumo Ducha Eléctrica': 9,
    'Consumo Lavadora de ropa': 3.52,
    'Consumo Secadora de ropa': 1.76,
    'Consumo Focos': 8.19,
    'Consumo Laptop': 1.8,
    'Consumo Celular': 5.52,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 212.2875,
    'Consumo Planilla': 186.88,
    Hogares: 28
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 3,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 45.39130435,
    'Consumo Licuadora': 3.922826087,
    'Consumo Microondas': 5.543478261,
    'Consumo Cocina de inducción': 35.2173913,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 3.009782609,
    'Consumo Tv LCD': 7.826086957,
    'Consumo PC Escritorio': 5.869565217,
    'Consumo Radio': 2.191304348,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.2282608696,
    'Consumo Ducha Eléctrica': 6.358695652,
    'Consumo Lavadora de ropa': 3.92173913,
    'Consumo Secadora de ropa': 1.434782609,
    'Consumo Focos': 8.804347826,
    'Consumo Laptop': 1.252173913,
    'Consumo Celular': 6.169565217,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 137.1413043,
    'Consumo Planilla': 127.6765217,
    Hogares: 460
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 4,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 34.36363636,
    'Consumo Licuadora': 5.394886364,
    'Consumo Microondas': 8.676136364,
    'Consumo Cocina de inducción': 10.57954545,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 3.190909091,
    'Consumo Tv LCD': 12.68181818,
    'Consumo PC Escritorio': 2.659090909,
    'Consumo Radio': 2.720454545,
    'Consumo Videojuegos': 0.1363636364,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.2897727273,
    'Consumo Ducha Eléctrica': 10.3125,
    'Consumo Lavadora de ropa': 5.525,
    'Consumo Secadora de ropa': 0.45,
    'Consumo Focos': 11.57045455,
    'Consumo Laptop': 4.009090909,
    'Consumo Celular': 9.095454545,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0.0340909091,
    'Consumo Electrodomésticos': 121.6892045,
    'Consumo Planilla': 164.2872727,
    Hogares: 57
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 4,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 38.11764706,
    'Consumo Licuadora': 3.507352941,
    'Consumo Microondas': 1.102941176,
    'Consumo Cocina de inducción': 8.823529412,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.95,
    'Consumo Tv LCD': 12.08823529,
    'Consumo PC Escritorio': 28.05882353,
    'Consumo Radio': 7.411764706,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 1.764705882,
    'Consumo Ducha Eléctrica': 15.33088235,
    'Consumo Lavadora de ropa': 5.176470588,
    'Consumo Secadora de ropa': 3.105882353,
    'Consumo Focos': 14.54117647,
    'Consumo Laptop': 3.494117647,
    'Consumo Celular': 5.347058824,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 149.8205882,
    'Consumo Planilla': 174.8470588,
    Hogares: 37
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 4,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 30.85714286,
    'Consumo Licuadora': 6.042857143,
    'Consumo Microondas': 8.946428571,
    'Consumo Cocina de inducción': 1.607142857,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 2.925,
    'Consumo Tv LCD': 3.642857143,
    'Consumo PC Escritorio': 0.6428571429,
    'Consumo Radio': 1.8,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.2142857143,
    'Consumo Ducha Eléctrica': 12.85714286,
    'Consumo Lavadora de ropa': 3.771428571,
    'Consumo Secadora de ropa': 1.754761905,
    'Consumo Focos': 6.385714286,
    'Consumo Laptop': 6.171428571,
    'Consumo Celular': 12.81428571,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 100.4333333,
    'Consumo Planilla': 128.6571429,
    Hogares: 43
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 6,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 186,
    'Consumo Licuadora': 13.5,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 3,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 4.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 22,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 19.5,
    'Consumo Laptop': 1.8,
    'Consumo Celular': 0,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 250,
    'Consumo Planilla': 110.08,
    Hogares: 129
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 6,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 1.1625,
    'Consumo Microondas': 3.75,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 3.25,
    'Consumo Tv LCD': 7.5,
    'Consumo PC Escritorio': 5.25,
    'Consumo Radio': 3.675,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 90,
    'Consumo Ventilador': 0.25,
    'Consumo Ducha Eléctrica': 3.75,
    'Consumo Lavadora de ropa': 4.4,
    'Consumo Secadora de ropa': 1.466666667,
    'Consumo Focos': 7.55,
    'Consumo Laptop': 2.7,
    'Consumo Celular': 5.3,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 176.0041667,
    'Consumo Planilla': 230.2666667,
    Hogares: 1080
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 6,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 4.3125,
    'Consumo Microondas': 11.25,
    'Consumo Cocina de inducción': 25,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 2.275,
    'Consumo Tv LCD': 37,
    'Consumo PC Escritorio': 3,
    'Consumo Radio': 5.25,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 7.5,
    'Consumo Lavadora de ropa': 10.26666667,
    'Consumo Secadora de ropa': 1.466666667,
    'Consumo Focos': 11.8,
    'Consumo Laptop': 10.2,
    'Consumo Celular': 14.2,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 179.5208333,
    'Consumo Planilla': 159.7466667,
    Hogares: 188
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 6,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 14.625,
    'Consumo Microondas': 1.25,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.95,
    'Consumo Tv LCD': 9.5,
    'Consumo PC Escritorio': 3,
    'Consumo Radio': 0.7,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.375,
    'Consumo Ducha Eléctrica': 11.25,
    'Consumo Lavadora de ropa': 8.066666667,
    'Consumo Secadora de ropa': 8.066666667,
    'Consumo Focos': 16.05,
    'Consumo Laptop': 2.1,
    'Consumo Celular': 12.3,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 125.2333333,
    'Consumo Planilla': 132.2,
    Hogares: 538
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 6,
    Ingreso: 'Más de 2400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 0,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 6,
    'Consumo Laptop': 0,
    'Consumo Celular': 0,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 42,
    'Consumo Planilla': 64,
    Hogares: 103
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 7,
    Ingreso: '1200 a 2400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 4.5,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 6,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 4.5,
    'Consumo Laptop': 0,
    'Consumo Celular': 1.8,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 52.8,
    'Consumo Planilla': 120,
    Hogares: 26
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 7,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 43.2,
    'Consumo Licuadora': 7.74,
    'Consumo Microondas': 8.25,
    'Consumo Cocina de inducción': 12,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 5.07,
    'Consumo Tv LCD': 4.2,
    'Consumo PC Escritorio': 16.2,
    'Consumo Radio': 2.73,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 9,
    'Consumo Lavadora de ropa': 7.48,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 39.24,
    'Consumo Laptop': 6.48,
    'Consumo Celular': 3.36,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 164.95,
    'Consumo Planilla': 168.656,
    Hogares: 132
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 7,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 3,
    'Consumo Microondas': 7.5,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 0,
    'Consumo Tv LCD': 21,
    'Consumo PC Escritorio': 3.375,
    'Consumo Radio': 4.2,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0.75,
    'Consumo Ducha Eléctrica': 3.75,
    'Consumo Lavadora de ropa': 0.3666666667,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 6,
    'Consumo Laptop': 0.3,
    'Consumo Celular': 34.2,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 120.4416667,
    'Consumo Planilla': 313.92,
    Hogares: 191
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 7,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 0,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 1.95,
    'Consumo Tv LCD': 0,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 0.9,
    'Consumo Laptop': 0,
    'Consumo Celular': 1.2,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 4.05,
    'Consumo Planilla': 40,
    Hogares: 97
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 8,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 3.375,
    'Consumo Microondas': 45,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 5.85,
    'Consumo Tv LCD': 0,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 11.25,
    'Consumo Lavadora de ropa': null,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 0,
    'Consumo Laptop': 0,
    'Consumo Celular': 24,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': null,
    'Consumo Planilla': 32,
    Hogares: 112
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 8,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 7.8,
    'Consumo Tv LCD': 12,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 3,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 3.6,
    'Consumo Laptop': 0,
    'Consumo Celular': 14.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 76.8,
    'Consumo Planilla': 88,
    Hogares: 88
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 8,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 2.25,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 3.9,
    'Consumo Tv LCD': 0,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0.7,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 0,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 26.4,
    'Consumo Secadora de ropa': 26.4,
    'Consumo Focos': 3.6,
    'Consumo Laptop': 0,
    'Consumo Celular': 0.6,
    'Consumo Auto eléctrico': 30,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 129.85,
    'Consumo Planilla': 280,
    Hogares: 16
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 14,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 7.8,
    'Consumo Tv LCD': 12,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 3,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 3.6,
    'Consumo Laptop': 0,
    'Consumo Celular': 14.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 76.8,
    'Consumo Planilla': 88,
    Hogares: 64
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 14,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 7.8,
    'Consumo Tv LCD': 12,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 3,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 3.6,
    'Consumo Laptop': 0,
    'Consumo Celular': 14.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 76.8,
    'Consumo Planilla': 88,
    Hogares: 28
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 14,
    Ingreso: 'Más de 2400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 7.8,
    'Consumo Tv LCD': 12,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 3,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 3.6,
    'Consumo Laptop': 0,
    'Consumo Celular': 14.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 76.8,
    'Consumo Planilla': 88,
    Hogares: 88
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 15,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 7.8,
    'Consumo Tv LCD': 12,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 3,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 3.6,
    'Consumo Laptop': 0,
    'Consumo Celular': 14.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 76.8,
    'Consumo Planilla': 88,
    Hogares: 15
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 16,
    Ingreso: 'Menos de 400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 7.8,
    'Consumo Tv LCD': 12,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 3,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 3.6,
    'Consumo Laptop': 0,
    'Consumo Celular': 14.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 76.8,
    'Consumo Planilla': 88,
    Hogares: 23
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 16,
    Ingreso: '400 a 800',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 7.8,
    'Consumo Tv LCD': 12,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 3,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 3.6,
    'Consumo Laptop': 0,
    'Consumo Celular': 14.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 76.8,
    'Consumo Planilla': 88,
    Hogares: 15
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 16,
    Ingreso: '800 a 1200',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 7.8,
    'Consumo Tv LCD': 12,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 3,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 3.6,
    'Consumo Laptop': 0,
    'Consumo Celular': 14.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 76.8,
    'Consumo Planilla': 88,
    Hogares: 23
  },
  {
    Región: 'Oriente',
    Provincia: 'Pastaza',
    Área: 'Urbano',
    Jefatura: 'Masculina',
    'Tipo de Hogar': 16,
    Ingreso: 'Más de 2400',
    'Consumo Refrigerador': 36,
    'Consumo Licuadora': 0,
    'Consumo Microondas': 0,
    'Consumo Cocina de inducción': 0,
    'Consumo Lavadora de platos': 0,
    'Consumo Televisor a color': 7.8,
    'Consumo Tv LCD': 12,
    'Consumo PC Escritorio': 0,
    'Consumo Radio': 0,
    'Consumo Videojuegos': 0,
    'Consumo Aire Acondicionado': 0,
    'Consumo Ventilador': 3,
    'Consumo Ducha Eléctrica': 0,
    'Consumo Lavadora de ropa': 0,
    'Consumo Secadora de ropa': 0,
    'Consumo Focos': 3.6,
    'Consumo Laptop': 0,
    'Consumo Celular': 14.4,
    'Consumo Auto eléctrico': 0,
    'Consumo Motos eléctricas': 0,
    'Consumo Electrodomésticos': 76.8,
    'Consumo Planilla': 88,
    Hogares: 88
  }
]
